learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


app_name = 'basic_app'

urlpatterns=[
    url(r'^$',views.base,name='base'),
    url(r'^relative/',views.relative,name='relative'),
    url(r'^other/',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^basicapp/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

def other(request):
    return render(request,'basic_app/other.html')

def base(request):
    return render(request,'basic_app/base.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav>
      <nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background: #e3f2fd;">
        <div class="container">
          <ul class="navbar-nav">
            <li><a class="navbar-brand" href="{%url 'index'%}">Home</a></li>
            <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="nav-link" href="{%url 'basic_app:other' %}">other</a></li>
            <li><a class="nav-link" href="{%url 'basic_app:relative' %}">relative</a></li>

          </ul>

        </div>
    </nav>
    <div class="container">
      {%block body_block%}
      <!-- anything outside this will be inherited using extend -->
      {%endblock%}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
<title>Home</title>
{%extends "basic_app/base.html"%}

  {%block body_block%}

    <h1>this is index page</h1>
    <h2>inherting from template tag</h2>
  {%endblock%}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
<title>other</title>
{%extends "basic_app/base.html" %}
  {%block body_block%}
    <h1>this is the other page</h1>
  {%endblock%}

learning_templates/templates/basic_app/relative_url_templates.html
{%extends 'basic_app/base.html'%}
  {%block body_block%}
    <h1>this is the realtive page</h1>
    <a href="{% url 'basic_app:other' %}">Link to other page</a><br>
    <a href="{% url 'admin:index'%}">link to admin page</a><br>
    <a href="{% url 'index' %}">home page</a>
    {%endblock%}