learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'
urlpatterns=[
    url(r'^register/$',views.register, name='register'),
    url(r'^login/$',views.user_login, name='login')

]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url,include
urlpatterns = [
    url(r'^$',views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout',views.user_logout, name='logout'),
    url(r'^special',views.special, name='special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here

class UserProfileInfo(models.Model):
    #creating a relationship
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    #adding extra attributes
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pic', blank= True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget= forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
    # portfolio = forms.URLField(required=False)
    # picture = forms.ImageField(required = False)
    class Meta():
        model = UserProfileInfo
        # fields = '__all__'
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return render(request,'basic_app/special.html')


def register(request):
    registered= False
    user_form= UserForm()
    profile_form = UserProfileInfoForm()
    if request.method =='POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            print(user)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit= False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            print(profile)
            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    return render(request,'basic_app/registration.html',{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered })



def user_login(request):

    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("your account is not active")
        else:
            print("someone tried to login and failed")
            print("username {} and password {}" .format(username,password))
            return HttpResponse("invalid credentials")
    else:
            return render(request,'basic_app/login.html')

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background: #e3f2fd;">
      <div class="container">
        <ul class= "navbar-nav">
          <li><a class="nav-brand" href="{%url 'index' %}">Django</a></li>
          <li><a class="nav-link" href="{%url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{%url 'basic_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            <li><a class="nav-link" href="{% url 'special' %}">special</a></li>

          {% else %}
            <li><a class="nav-link" href="{% url 'basic_app:login' %}">Login</a></li>
            
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {%block body_block%}
      {%endblock%}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{%extends 'basic_app/base.html'%}
<title>Home</title>
{%block body_block%}

<div class="jumbotron">
<h1>Hi Welcome to My web</h1>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}
<title>Home</title>
{%block body_block%}
<div class="jumbotron">
  <h1>Login here</h1>
  <form action = "{% url 'basic_app:login'%}" method="post">
    {% csrf_token %}
  <label for="username">Username</label>
  <input type="text" name="username" placeholder="username">
  <label for="password">Password</label>
  <input type="password" name="password">
  <input type="submit" class="btn btn-primary" value="signup">
</form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{%extends 'basic_app/base.html'%}
{%load staticfiles %}
<title>Register</title>
{%block body_block%}
<div class="jumbotron">
    {%if registered%}
      <h1>thank you for registration</h1>
    {%else%}
      <h2>Please fill the registration form</h2>
      <form   enctype="multipart/form-data" method="POST">
        {%csrf_token%}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" class="btn btn-primary" value="submit">
        {%endif%}

      </form>
    </div>

{%endblock%}

learning_users/templates/basic_app/special.html
<!DOCTYPE html>
<title>Coffee</title>
{%extends 'basic_app/base.html'%}
{%block body_block%}
    <style>
    .boxy{

      text-align: center;
    }
    .img{
      height:200px;
      margin-bottom: 10px;
    }

</style>
<nav class="navbar navbar-expand-lg navbar-light " style="background: #2222;">
  <div class="container">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a href="#" class="navbar-brand">Welcome</a>

      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="bootsignin.html">Sign In</a></li>

      </ul>
    </div>
    </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="jumbotron">
        <!-- <div class="col-lg-12"> -->
          <div class="boxy">

        <h1>Coffee Lover Project</h1>
        <h3> Welcome</h3>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    <!-- </div> -->
    </div>
  </div>
</div>
<div class="container">
  list of coffees
<ul>
<li><a id="list" href="https://cdn.stocksnap.io/img-thumbs/960w/QU7KW07CMU.jpg" target="_blank">one</a></li>
  <li><a id="list" href="https://cdn.stocksnap.io/img-thumbs/280h/GZCFF9JJE7.jpg" target="_blank">two</a></li>
    <li><a id="list" href="https://cdn.stocksnap.io/img-thumbs/280h/ZJZWZJL0DB.jpg" target="_blank">three</a></li>
      <li><a id="list" href="https://cdn.stocksnap.io/img-thumbs/280h/P9EOEJ2HZE.jpg" target="_blank">four</a></li>
        <li><a id="list" href="https://cdn.stocksnap.io/img-thumbs/280h/DUCGSX7XFO.jpg" target="_blank">five</a></li>
          <li><a id="list" href="https://cdn.stocksnap.io/img-thumbs/280h/8OIVRDR8V0.jpg" target="_blank">six</a></li>

  </ul>
  </div>
<div class="container">

  <div class="row">
    <h1 class="col-lg-12">Picture of Coffee</h1>
      <img src="https://cdn.stocksnap.io/img-thumbs/960w/QU7KW07CMU.jpg" class="col-md-4 col-6 img img-thumbnail"/>
      <img src="https://cdn.stocksnap.io/img-thumbs/280h/GZCFF9JJE7.jpg" class="col-md-4 col-6 img img-thumbnail"/>
      <img src="https://cdn.stocksnap.io/img-thumbs/280h/ZJZWZJL0DB.jpg" class="col-md-4 col-6 img img-thumbnail"/>
      <img src="https://cdn.stocksnap.io/img-thumbs/280h/P9EOEJ2HZE.jpg" class="col-md-6 col-6 img img-thumbnail"/>
      <img src="https://cdn.stocksnap.io/img-thumbs/280h/DUCGSX7XFO.jpg" class="col-md-6 col-6 img img-thumbnail"/>
      <img src="https://cdn.stocksnap.io/img-thumbs/280h/8OIVRDR8V0.jpg" class="col-md-4 col-6 img img-thumbnail"/>

    </div>

  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%endblock%}